# Generated by Django 4.2.16 on 2024-10-30 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.TextField(blank=True, null=True)),
                ("display_on_profile", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
