# Generated by Django 4.2.16 on 2024-10-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_readinggoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reading_goal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="ReadingGoal",
        ),
    ]
