# Generated by Django 4.2.16 on 2024-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="buy_link",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="img_url",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
