# Generated by Django 4.2.16 on 2024-10-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='genre',
            field=models.CharField(choices=[('FICT', 'Fiction'), ('NFICT', 'Non-Fiction'), ('SCI_FI', 'Science Fiction'), ('MYST', 'Mystery'), ('ROM', 'Romance'), ('THRILL', 'Thriller'), ('HORROR', 'Horror'), ('FANTASY', 'Fantasy'), ('BIOG', 'Biography'), ('HIST', 'Historical'), ('CHILD', 'Children'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
