# Generated by Django 4.2.16 on 2024-10-19 23:47

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_bookreview_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='review_files/', validators=[reviews.models.validate_review_file]),
        ),
    ]
