# Generated by Django 4.2.16 on 2024-10-20 00:38

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_bookreview_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[reviews.models.validate_review_file]),
        ),
    ]
