# Generated by Django 4.2.16 on 2024-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_bookreview_file_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bookreview',
            name='file_description',
            field=models.TextField(blank=True, help_text='Detailed description of the file', null=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='file_keywords',
            field=models.CharField(blank=True, help_text='Keywords describing the file content', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='file_title',
            field=models.CharField(blank=True, help_text='Title of the uploaded file', max_length=255, null=True),
        ),
    ]
