# Generated by Django 4.2.16 on 2024-10-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_bookreview_options_bookreview_file_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='file_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
