# Generated by Django 4.2.16 on 2024-11-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_comment_options_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
