# Generated by Django 4.2.16 on 2024-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_bookreview_author_alter_bookreview_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='genre',
            field=models.CharField(choices=[('FICT', 'Fiction'), ('NFICT', 'Non-Fiction'), ('SCI_FI', 'Science Fiction'), ('MYST', 'Mystery'), ('ROM', 'Romance'), ('THRILL', 'Thriller'), ('HORROR', 'Horror'), ('FANTASY', 'Fantasy'), ('BIOG', 'Biography'), ('HIST', 'Historical'), ('CHILD', 'Children'), ('OTHER', 'Other')], default='OTHER', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
