# Generated by Django 4.2.16 on 2024-11-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_bookreview_author_alter_bookreview_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='file_keywords',
            field=models.CharField(blank=True, help_text='Keywords describing the file content', max_length=1000, null=True),
        ),
    ]
