# Generated by Django 4.2.16 on 2024-11-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_bookreview_file_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='file_keywords',
            field=models.CharField(blank=True, help_text='Keywords describing the file content', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='genre',
            field=models.CharField(choices=[('FICT', 'Fiction'), ('NFICT', 'Non-Fiction'), ('SCI_FI', 'Science Fiction'), ('MYST', 'Mystery'), ('ROM', 'Romance'), ('THRILL', 'Thriller'), ('HORROR', 'Horror'), ('FANTASY', 'Fantasy'), ('BIOG', 'Biography'), ('HIST', 'Historical'), ('CHILD', 'Children'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
