# Generated by Django 4.2.16 on 2024-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviewmembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookreviewmembership',
            name='left_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
