
# Generated by Django 4.2.16 on 2024-12-04 15:26

from django.db import migrations

def set_memberships_active(apps, schema_editor):
    BookReviewMembership = apps.get_model('reviews', 'BookReviewMembership')
    BookReviewMembership.objects.all().update(is_active=True)

def reverse_memberships_active(apps, schema_editor):
    BookReviewMembership = apps.get_model('reviews', 'BookReviewMembership')
    BookReviewMembership.objects.all().update(is_active=False)

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_bookreviewmembership_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(set_memberships_active, reverse_memberships_active),
    ]