# Generated by Django 4.2.16 on 2024-12-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_set_existing_memberships_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreviewmembership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bookreviewmembership',
            name='left_date',
        ),
    ]
