# Generated by Django 4.2.16 on 2024-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_remove_bookreviewmembership_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreviewmembership',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='bookreviewmembership',
            name='left_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
