# Generated by Django 4.2.16 on 2024-12-04 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_remove_bookreviewmembership_joined_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreviewmembership',
            name='left_date',
        ),
        migrations.AddField(
            model_name='bookreviewmembership',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 20, 27, 57, 888785, tzinfo=datetime.timezone.utc)),
        ),
    ]
