# Generated by Django 4.2.16 on 2024-12-04 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_remove_bookreviewmembership_left_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviewmembership',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 20, 57, 45, 338645, tzinfo=datetime.timezone.utc)),
        ),
    ]
