# Generated by Django 4.2.16 on 2024-12-04 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_alter_bookreviewmembership_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviewmembership',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 21, 19, 25, 688422, tzinfo=datetime.timezone.utc)),
        ),
    ]
