# Generated by Django 4.2.16 on 2024-12-05 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_alter_bookreviewmembership_joined_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookreviewmembership',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 2, 7, 52, 916349, tzinfo=datetime.timezone.utc)),
        ),
    ]
