# Generated by Django 4.2.16 on 2024-12-05 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_alter_joinrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviewmembership',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 2, 8, 16, 809830, tzinfo=datetime.timezone.utc)),
        ),
    ]
