# Generated by Django 4.2.16 on 2024-12-05 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_alter_bookreviewmembership_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviewmembership',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
